name: flutter_dev
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dio: ^3.0.8
  crypto: ^2.0.6
  #sqflite插件
  sqflite: ^1.1.0
  # 本地化存储 https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.7+3
  # 二维码生成 https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0
  # 二维码扫描 https://pub.dev/packages/barcode_scan
  barcode_scan: ^3.0.1
  # 进度条 https://pub.flutter-io.cn/packages/percent_indicator
  percent_indicator: ^2.1.5

  english_words: ^3.1.0
  flustars: ^0.3.2
  flutter_swiper: ^1.1.6
  pull_to_refresh: ^1.6.0
  extended_nested_scroll_view: ^1.0.0
  video_player: ^0.10.11+1
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.7+3
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  # 弹框 https://pub.dev/packages/fluttertoast#-installing-tab-
  fluttertoast: ^5.0.1
  awesome_dialog: ^1.1.3
  charts_flutter: ^0.9.0
  provide: ^1.0.2
  # 轻量级HTML解析
  flutter_html: ^1.0.0
  # InAppWebView
  flutter_inappwebview: ^4.0.0+4
  keyboard_actions: 3.2.0
  # 加密 https://pub.flutter-io.cn/packages/encrypt
  encrypt: ^4.0.2
  # 底部弹出 日期选择器 单列多列  https://pub.dev/packages/flutter_picker
  flutter_picker: 1.1.0
  # 时间格式转换 https://pub.dev/packages/date_format
  date_format: 1.0.8
  # 图片手势 https://pub.dev/packages/photo_view
  photo_view: 0.9.2
  # 相册多图选择 https://pub.dev/packages/photo
  photo: 0.4.8
#  multi_image_picker: ^4.6.1
  # 监测网络状态 https://pub.dev/packages/connectivity
  connectivity: ^0.4.9
  # webview https://pub.flutter-io.cn/packages/webview_flutter#-installing-tab-
  webview_flutter: ^0.3.19+9

  # 组件库 https://www.flui.xin/guide.html
  flui: 0.8.0
  # 加载框 https://pub.flutter-io.cn/packages/flutter_progress_dialog
  flutter_progress_dialog: ^0.1.0
  # 加载框 https://pub.flutter-io.cn/packages/oktoast#-readme-tab-
  oktoast: 2.3.1+1
  #下拉选择筛选
  dropdown_search: ^0.4.4
  #select_days_week: ^0.1.1
  # 源码已修改  升级请谨慎  去掉了下划线
  multiple_select: 0.1.23
  # 加载loading
  flutter_spinkit: "^4.1.2"
  # 获取手机信息
  device_info : ^0.2.0
  signature: ^2.0.0   #签名

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - resources/
    - resources/images/

  fonts:
    - family: UniTortred
      fonts:
        - asset: fonts/UniTortred.ttf
    #          style: italic
    #  fonts:
    #    - family: UniTortred
    #      fonts:
    #        -asset: font/UniTortred.ttf
    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
